#!/usr/bin/env bash
# install NGINX server
sudo apt-get update -y
sudo apt-get install nginx -y

# configure Nginx to be listening on port 80
sudo ufw allow 'Nginx HTTP'

# configure Nginx server to return a page that contains the string Hello World!
echo "Hello World!" | sudo tee /var/www/html/index*
# reload Nginx configs
sudo service nginx reload
