#!/usr/bin/env bash

# Install NGINX server
sudo apt-get update -y
sudo apt-get install nginx -y

# Configure Nginx to be listening on port 80
sudo ufw allow 'Nginx HTTP'

# Configure Nginx server to return a page that contains the string Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure redirect_me
sudo sed -i '/location \/redirect_me {/a \\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default

# Reload Nginx configs
sudo service nginx restart

