#!/usr/bin/env bash
# Installs and configures HA Proxy
sudo apt update
sudo apt install haproxy

# configure HA Proxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
config="
frontend http
	bind *:80
	mode http
	default_backend web_backend

backend web_backend
	balance roundrobin
	server web-01 100.26.173.252:80 check
	server web-02 54.160.114.174:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg >> /dev/null

# restart the HAproxy
sudo service haproxy restart
