#!/usr/bin/env bash
# fix curl: (7) Failed to connect to 0 port 80: Connection refused error
ls -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default

# reload nginx
sudo service nginx restart;
