#!/usr/bin/env bash
# fix curl: (7) Failed to connect to 0 port 80: Connection refused error 
sed -i '/8080/80' /etc/nginx/sites-anabled/default
sudo service nginx restart;
pkill -f --signal 1 "/usr/bin/nginx"
