#!/usr/bin/env bash
#a Bash script that groups visitors by IP and HTTP status code, and displays this data.
 awk -F'"' '{ split($1, a, "-") ; split($3, arr, " ") ; lines[NR] = arr[2] " " a[1] arr[1] } END { asort(lines) ; for (i = 1; i <= NR; i++) print lines[i] }' apache-access.log | sort -nr
