#!/usr/bin/env bash
#displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
for item in * ; do
    [[ -e "19-to_file_or_not_to_file" ]] || break
    echo "$item" | cut -d '-' -f 2
done
