#!/usr/bin/env bash
# configures a firewall to blocks all incoming traffic, except on ports 80(HTTP), 443(HTTPS) and 22(SSh)
sudo apt update -y
sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw --force enable
