#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
echo -e "127.0.0.2\tlocalhost" >> /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
