#!/usr/bin/env bash
# configures nginx to run as nginx user
sed -i '/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
# configures nginx to listen on port 8080
sed -i '/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
