#!/usr/bin/env bash
# configures nginx to run as nginx user
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod +r /etc/nginx/nginx.conf
# configures nginx to listen on port 8080
sed -i '/listen 80/listen 8080/' /etc/nginx/sites-available/default
service nginx restart
