#!/usr/bin/env bash
# configures nginx to listen on port 8080
sed -i -e 's|#user www-data|user nginx|' -e 's|80|8080|' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
