#!/usr/bin/env bash
# configures nginx to run as nginx user, listen on port 8080
sed -i -e '/#user www-data/s/user nginx/' -e '/listen 80/s/listen 8080/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart

