#!/usr/bin/env bash
# reloads gunicorn without any downtime
#shellcheck disable=SC2009
# ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP

PIDS=$(pgrep -f 'gunicorn')

for pid in $PIDS; do
	kill -s TERM "$pid"
	wait "$pid"
done
